
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.Objects;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author USER
 */
public class HalamanProduk extends javax.swing.JFrame {
    int x = 0;
    /**
     * Creates new form HlamanTes
     */
    public HalamanProduk() {
        initComponents();
        
        Dimension screenSize = 
        Toolkit.getDefaultToolkit().getScreenSize();
            Dimension frameSize = this.getSize();
            if (frameSize.height > screenSize.height) {
                frameSize.height = screenSize.height;
            }
            if (frameSize.width > screenSize.width) {
                frameSize.width = screenSize.width;
            }
            this.setLocation(
                    (screenSize.width - frameSize.width) / 2, 
                    (screenSize.height - frameSize.height) / 2); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        panelMenu1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        menu1 = new javax.swing.JLabel();
        harga1 = new javax.swing.JLabel();
        pesan1 = new javax.swing.JButton();
        jumlah1 = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tbdata = new javax.swing.JTable();
        panelMenu3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        menu2 = new javax.swing.JLabel();
        harga2 = new javax.swing.JLabel();
        pesan2 = new javax.swing.JButton();
        jumlah2 = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();
        panelMenu7 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        menu3 = new javax.swing.JLabel();
        harga3 = new javax.swing.JLabel();
        pesan3 = new javax.swing.JButton();
        jumlah3 = new javax.swing.JSpinner();
        jLabel14 = new javax.swing.JLabel();
        panelMenu8 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        menu4 = new javax.swing.JLabel();
        harga4 = new javax.swing.JLabel();
        pesan4 = new javax.swing.JButton();
        jumlah4 = new javax.swing.JSpinner();
        jLabel16 = new javax.swing.JLabel();
        panelMenu9 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        menu5 = new javax.swing.JLabel();
        harga5 = new javax.swing.JLabel();
        pesan5 = new javax.swing.JButton();
        jumlah5 = new javax.swing.JSpinner();
        jLabel18 = new javax.swing.JLabel();
        panelMenu10 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        menu6 = new javax.swing.JLabel();
        harga6 = new javax.swing.JLabel();
        pesan6 = new javax.swing.JButton();
        jumlah6 = new javax.swing.JSpinner();
        jLabel20 = new javax.swing.JLabel();
        panelMenu11 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        menu7 = new javax.swing.JLabel();
        harga7 = new javax.swing.JLabel();
        pesan7 = new javax.swing.JButton();
        jumlah7 = new javax.swing.JSpinner();
        jLabel22 = new javax.swing.JLabel();
        panelMenu12 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        menu8 = new javax.swing.JLabel();
        harga8 = new javax.swing.JLabel();
        pesan8 = new javax.swing.JButton();
        jumlah8 = new javax.swing.JSpinner();
        jLabel24 = new javax.swing.JLabel();
        panelMenu13 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        menu9 = new javax.swing.JLabel();
        harga9 = new javax.swing.JLabel();
        pesan9 = new javax.swing.JButton();
        jumlah9 = new javax.swing.JSpinner();
        jLabel26 = new javax.swing.JLabel();
        konfirButton = new javax.swing.JLabel();
        hapusPesan = new javax.swing.JButton();
        totalTxt = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        metodePembayaran = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FOOD.IF");

        jScrollPane2.setPreferredSize(new java.awt.Dimension(835, 505));

        jPanel1.setBackground(new java.awt.Color(169, 172, 169));
        jPanel1.setPreferredSize(new java.awt.Dimension(830, 1000));

        panelMenu1.setBackground(new java.awt.Color(191, 195, 186));
        panelMenu1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelMenu1.setForeground(new java.awt.Color(255, 255, 255));
        panelMenu1.setPreferredSize(new java.awt.Dimension(250, 250));
        panelMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelMenu1MouseClicked(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MieGoreng.jpg"))); // NOI18N
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        menu1.setText("Mie Goreng");

        harga1.setText("Rp. 13000");

        pesan1.setText("Pesan");
        pesan1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pesan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesan1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Jumlah");

        javax.swing.GroupLayout panelMenu1Layout = new javax.swing.GroupLayout(panelMenu1);
        panelMenu1.setLayout(panelMenu1Layout);
        panelMenu1Layout.setHorizontalGroup(
            panelMenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenu1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGroup(panelMenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMenu1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jumlah1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelMenu1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(pesan1))
                    .addGroup(panelMenu1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(panelMenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(harga1)
                            .addComponent(menu1))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelMenu1Layout.setVerticalGroup(
            panelMenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenu1Layout.createSequentialGroup()
                .addGroup(panelMenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMenu1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(menu1)
                        .addGap(18, 18, 18)
                        .addComponent(harga1)
                        .addGap(15, 15, 15)
                        .addGroup(panelMenu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jumlah1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addComponent(pesan1))
                    .addGroup(panelMenu1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Tbdata.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nama Pesanan", "Jumlah", "Harga"
            }
        ));
        jScrollPane1.setViewportView(Tbdata);

        panelMenu3.setBackground(new java.awt.Color(191, 195, 186));
        panelMenu3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelMenu3.setForeground(new java.awt.Color(255, 255, 255));
        panelMenu3.setPreferredSize(new java.awt.Dimension(250, 250));
        panelMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelMenu3MouseClicked(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NasiGoreng.jpg"))); // NOI18N
        jLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        menu2.setText("Nasi Goreng");

        harga2.setText("Rp. 15000");

        pesan2.setText("Pesan");
        pesan2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pesan2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesan2ActionPerformed(evt);
            }
        });

        jLabel10.setText("Jumlah");

        javax.swing.GroupLayout panelMenu3Layout = new javax.swing.GroupLayout(panelMenu3);
        panelMenu3.setLayout(panelMenu3Layout);
        panelMenu3Layout.setHorizontalGroup(
            panelMenu3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenu3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGroup(panelMenu3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMenu3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jumlah2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelMenu3Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(pesan2))
                    .addGroup(panelMenu3Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(panelMenu3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(harga2)
                            .addComponent(menu2))))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        panelMenu3Layout.setVerticalGroup(
            panelMenu3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenu3Layout.createSequentialGroup()
                .addGroup(panelMenu3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMenu3Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(menu2)
                        .addGap(18, 18, 18)
                        .addComponent(harga2)
                        .addGap(15, 15, 15)
                        .addGroup(panelMenu3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jumlah2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addComponent(pesan2))
                    .addGroup(panelMenu3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelMenu7.setBackground(new java.awt.Color(191, 195, 186));
        panelMenu7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelMenu7.setForeground(new java.awt.Color(255, 255, 255));
        panelMenu7.setPreferredSize(new java.awt.Dimension(250, 250));
        panelMenu7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelMenu7MouseClicked(evt);
            }
        });

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NasiGorengMawut.jpg"))); // NOI18N
        jLabel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        menu3.setText("Nasi Mawut");

        harga3.setText("Rp. 17000");

        pesan3.setText("Pesan");
        pesan3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pesan3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesan3ActionPerformed(evt);
            }
        });

        jLabel14.setText("Jumlah");

        javax.swing.GroupLayout panelMenu7Layout = new javax.swing.GroupLayout(panelMenu7);
        panelMenu7.setLayout(panelMenu7Layout);
        panelMenu7Layout.setHorizontalGroup(
            panelMenu7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenu7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addGroup(panelMenu7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMenu7Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jumlah3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelMenu7Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(pesan3))
                    .addGroup(panelMenu7Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(panelMenu7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(harga3)
                            .addComponent(menu3))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        panelMenu7Layout.setVerticalGroup(
            panelMenu7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenu7Layout.createSequentialGroup()
                .addGroup(panelMenu7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMenu7Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(menu3)
                        .addGap(18, 18, 18)
                        .addComponent(harga3)
                        .addGap(15, 15, 15)
                        .addGroup(panelMenu7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jumlah3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addGap(18, 18, 18)
                        .addComponent(pesan3))
                    .addGroup(panelMenu7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel13)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelMenu8.setBackground(new java.awt.Color(191, 195, 186));
        panelMenu8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelMenu8.setForeground(new java.awt.Color(255, 255, 255));
        panelMenu8.setPreferredSize(new java.awt.Dimension(250, 250));
        panelMenu8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelMenu8MouseClicked(evt);
            }
        });

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Burger.jpg"))); // NOI18N
        jLabel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        menu4.setText("Burger");

        harga4.setText("Rp. 30000");

        pesan4.setText("Pesan");
        pesan4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pesan4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesan4ActionPerformed(evt);
            }
        });

        jLabel16.setText("Jumlah");

        javax.swing.GroupLayout panelMenu8Layout = new javax.swing.GroupLayout(panelMenu8);
        panelMenu8.setLayout(panelMenu8Layout);
        panelMenu8Layout.setHorizontalGroup(
            panelMenu8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenu8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addGroup(panelMenu8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMenu8Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jumlah4, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelMenu8Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(pesan4))
                    .addGroup(panelMenu8Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(panelMenu8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(harga4)
                            .addComponent(menu4))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelMenu8Layout.setVerticalGroup(
            panelMenu8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenu8Layout.createSequentialGroup()
                .addGroup(panelMenu8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMenu8Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(menu4)
                        .addGap(18, 18, 18)
                        .addComponent(harga4)
                        .addGap(15, 15, 15)
                        .addGroup(panelMenu8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jumlah4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addGap(18, 18, 18)
                        .addComponent(pesan4))
                    .addGroup(panelMenu8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel15)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelMenu9.setBackground(new java.awt.Color(191, 195, 186));
        panelMenu9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelMenu9.setForeground(new java.awt.Color(255, 255, 255));
        panelMenu9.setPreferredSize(new java.awt.Dimension(250, 250));
        panelMenu9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelMenu9MouseClicked(evt);
            }
        });

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pizza.jpg"))); // NOI18N
        jLabel17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        menu5.setText("Pizza");

        harga5.setText("Rp. 75000");

        pesan5.setText("Pesan");
        pesan5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pesan5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesan5ActionPerformed(evt);
            }
        });

        jLabel18.setText("Jumlah");

        javax.swing.GroupLayout panelMenu9Layout = new javax.swing.GroupLayout(panelMenu9);
        panelMenu9.setLayout(panelMenu9Layout);
        panelMenu9Layout.setHorizontalGroup(
            panelMenu9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenu9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addGroup(panelMenu9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMenu9Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jumlah5, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelMenu9Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(pesan5))
                    .addGroup(panelMenu9Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(panelMenu9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(harga5)
                            .addComponent(menu5))))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        panelMenu9Layout.setVerticalGroup(
            panelMenu9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenu9Layout.createSequentialGroup()
                .addGroup(panelMenu9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMenu9Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(menu5)
                        .addGap(18, 18, 18)
                        .addComponent(harga5)
                        .addGap(15, 15, 15)
                        .addGroup(panelMenu9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jumlah5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18))
                        .addGap(18, 18, 18)
                        .addComponent(pesan5))
                    .addGroup(panelMenu9Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel17)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelMenu10.setBackground(new java.awt.Color(191, 195, 186));
        panelMenu10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelMenu10.setForeground(new java.awt.Color(255, 255, 255));
        panelMenu10.setPreferredSize(new java.awt.Dimension(250, 250));
        panelMenu10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelMenu10MouseClicked(evt);
            }
        });

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ramen.jpg"))); // NOI18N
        jLabel19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        menu6.setText("Ramen");

        harga6.setText("Rp. 35000");

        pesan6.setText("Pesan");
        pesan6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pesan6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesan6ActionPerformed(evt);
            }
        });

        jLabel20.setText("Jumlah");

        javax.swing.GroupLayout panelMenu10Layout = new javax.swing.GroupLayout(panelMenu10);
        panelMenu10.setLayout(panelMenu10Layout);
        panelMenu10Layout.setHorizontalGroup(
            panelMenu10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenu10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19)
                .addGroup(panelMenu10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMenu10Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jumlah6, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelMenu10Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(pesan6))
                    .addGroup(panelMenu10Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(panelMenu10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(harga6)
                            .addComponent(menu6))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        panelMenu10Layout.setVerticalGroup(
            panelMenu10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenu10Layout.createSequentialGroup()
                .addGroup(panelMenu10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMenu10Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(menu6)
                        .addGap(18, 18, 18)
                        .addComponent(harga6)
                        .addGap(15, 15, 15)
                        .addGroup(panelMenu10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jumlah6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20))
                        .addGap(18, 18, 18)
                        .addComponent(pesan6))
                    .addGroup(panelMenu10Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel19)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelMenu11.setBackground(new java.awt.Color(191, 195, 186));
        panelMenu11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelMenu11.setForeground(new java.awt.Color(255, 255, 255));
        panelMenu11.setPreferredSize(new java.awt.Dimension(250, 250));
        panelMenu11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelMenu11MouseClicked(evt);
            }
        });

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Water.png"))); // NOI18N
        jLabel21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        menu7.setText("Air Mineral");

        harga7.setText("Rp. 5000");

        pesan7.setText("Pesan");
        pesan7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pesan7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesan7ActionPerformed(evt);
            }
        });

        jLabel22.setText("Jumlah");

        javax.swing.GroupLayout panelMenu11Layout = new javax.swing.GroupLayout(panelMenu11);
        panelMenu11.setLayout(panelMenu11Layout);
        panelMenu11Layout.setHorizontalGroup(
            panelMenu11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenu11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21)
                .addGroup(panelMenu11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMenu11Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jumlah7, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelMenu11Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(pesan7))
                    .addGroup(panelMenu11Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(panelMenu11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(harga7)
                            .addComponent(menu7))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelMenu11Layout.setVerticalGroup(
            panelMenu11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenu11Layout.createSequentialGroup()
                .addGroup(panelMenu11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMenu11Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(menu7)
                        .addGap(18, 18, 18)
                        .addComponent(harga7)
                        .addGap(15, 15, 15)
                        .addGroup(panelMenu11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jumlah7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22))
                        .addGap(18, 18, 18)
                        .addComponent(pesan7))
                    .addGroup(panelMenu11Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel21)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelMenu12.setBackground(new java.awt.Color(191, 195, 186));
        panelMenu12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelMenu12.setForeground(new java.awt.Color(255, 255, 255));
        panelMenu12.setPreferredSize(new java.awt.Dimension(250, 250));
        panelMenu12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelMenu12MouseClicked(evt);
            }
        });

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EsTeh.jpg"))); // NOI18N
        jLabel23.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        menu8.setText("Es Teh");

        harga8.setText("Rp. 5000");

        pesan8.setText("Pesan");
        pesan8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pesan8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesan8ActionPerformed(evt);
            }
        });

        jLabel24.setText("Jumlah");

        javax.swing.GroupLayout panelMenu12Layout = new javax.swing.GroupLayout(panelMenu12);
        panelMenu12.setLayout(panelMenu12Layout);
        panelMenu12Layout.setHorizontalGroup(
            panelMenu12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenu12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel23)
                .addGroup(panelMenu12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMenu12Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jumlah8, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelMenu12Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(pesan8))
                    .addGroup(panelMenu12Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(panelMenu12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(harga8)
                            .addComponent(menu8))))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        panelMenu12Layout.setVerticalGroup(
            panelMenu12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenu12Layout.createSequentialGroup()
                .addGroup(panelMenu12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMenu12Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(menu8)
                        .addGap(18, 18, 18)
                        .addComponent(harga8)
                        .addGap(15, 15, 15)
                        .addGroup(panelMenu12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jumlah8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24))
                        .addGap(18, 18, 18)
                        .addComponent(pesan8))
                    .addGroup(panelMenu12Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel23)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelMenu13.setBackground(new java.awt.Color(191, 195, 186));
        panelMenu13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelMenu13.setForeground(new java.awt.Color(255, 255, 255));
        panelMenu13.setPreferredSize(new java.awt.Dimension(250, 250));
        panelMenu13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelMenu13MouseClicked(evt);
            }
        });

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EsJeruk.jpg"))); // NOI18N
        jLabel25.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        menu9.setText("Es Jeruk");

        harga9.setText("Rp. 8000");

        pesan9.setText("Pesan");
        pesan9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pesan9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesan9ActionPerformed(evt);
            }
        });

        jLabel26.setText("Jumlah");

        javax.swing.GroupLayout panelMenu13Layout = new javax.swing.GroupLayout(panelMenu13);
        panelMenu13.setLayout(panelMenu13Layout);
        panelMenu13Layout.setHorizontalGroup(
            panelMenu13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenu13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel25)
                .addGroup(panelMenu13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMenu13Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jumlah9, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelMenu13Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(pesan9))
                    .addGroup(panelMenu13Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(panelMenu13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(harga9)
                            .addComponent(menu9))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        panelMenu13Layout.setVerticalGroup(
            panelMenu13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenu13Layout.createSequentialGroup()
                .addGroup(panelMenu13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMenu13Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(menu9)
                        .addGap(18, 18, 18)
                        .addComponent(harga9)
                        .addGap(15, 15, 15)
                        .addGroup(panelMenu13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jumlah9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel26))
                        .addGap(18, 18, 18)
                        .addComponent(pesan9))
                    .addGroup(panelMenu13Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel25)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        konfirButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logoGabung.png"))); // NOI18N
        konfirButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        konfirButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                konfirButtonMouseClicked(evt);
            }
        });

        hapusPesan.setText("Hapus Pesanan");
        hapusPesan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        hapusPesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusPesanActionPerformed(evt);
            }
        });

        totalTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalTxtActionPerformed(evt);
            }
        });

        jButton2.setText("Tampilkan total harga");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        metodePembayaran.setText("Pilih Metode Pembayaran");
        metodePembayaran.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        metodePembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                metodePembayaranActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jLabel2.setText("KATEGORI MENU MAKANAN");

        jLabel4.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jLabel4.setText("KATEGORI MENU MINUMAN");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 608, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(panelMenu1, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                            .addComponent(panelMenu8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                            .addComponent(panelMenu11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelMenu9, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panelMenu3, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panelMenu12, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(panelMenu7, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(panelMenu10, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(panelMenu13, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(totalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(hapusPesan)
                                        .addGap(26, 26, 26)
                                        .addComponent(jButton2)))
                                .addGap(43, 43, 43))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(86, 86, 86)
                                .addComponent(metodePembayaran))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addComponent(konfirButton)))
                        .addContainerGap())))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(378, 378, 378)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(376, 376, 376)
                        .addComponent(jLabel2)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelMenu3, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelMenu1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelMenu7, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelMenu8, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelMenu9, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelMenu10, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelMenu13, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelMenu11, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelMenu12, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hapusPesan)
                            .addComponent(jButton2))
                        .addGap(18, 18, 18)
                        .addComponent(totalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(metodePembayaran)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(konfirButton)))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(875, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pesan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesan1ActionPerformed
         if ((int) jumlah1.getValue() == 0){
            JOptionPane.showMessageDialog(null, "Masukkan setidaknya 1");
        } else {
            JOptionPane.showMessageDialog(null, "Berhasil ditambahkan");
            int y = 13000 * (int) jumlah1.getValue();
            Tbdata.setValueAt(menu1.getText(), x, 0);
            Tbdata.setValueAt(jumlah1.getValue(), x, 1);
            Tbdata.setValueAt(y, x, 2);
            x = x + 1;
        }
    }//GEN-LAST:event_pesan1ActionPerformed

    private void panelMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMenu1MouseClicked

    }//GEN-LAST:event_panelMenu1MouseClicked

    private void pesan2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesan2ActionPerformed
        if ((int) jumlah2.getValue() == 0){
            JOptionPane.showMessageDialog(null, "Masukkan setidaknya 1");
        } else {
            JOptionPane.showMessageDialog(null, "Berhasil ditambahkan");
            int y = 15000 * (int) jumlah2.getValue();
            Tbdata.setValueAt(menu2.getText(), x, 0);
            Tbdata.setValueAt(jumlah2.getValue(), x, 1);
            Tbdata.setValueAt(y, x, 2);
            x = x + 1;
        }
    }//GEN-LAST:event_pesan2ActionPerformed

    private void panelMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMenu3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_panelMenu3MouseClicked

    private void pesan3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesan3ActionPerformed
        if ((int) jumlah3.getValue() == 0){
            JOptionPane.showMessageDialog(null, "Masukkan setidaknya 1");
        } else {
            JOptionPane.showMessageDialog(null, "Berhasil ditambahkan");
            int y = 17000 * (int) jumlah3.getValue();
            Tbdata.setValueAt(menu3.getText(), x, 0);
            Tbdata.setValueAt(jumlah3.getValue(), x, 1);
            Tbdata.setValueAt(y, x, 2);
            x = x + 1;
        }
    }//GEN-LAST:event_pesan3ActionPerformed

    private void panelMenu7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMenu7MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_panelMenu7MouseClicked

    private void pesan4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesan4ActionPerformed
        if ((int) jumlah4.getValue() == 0){
            JOptionPane.showMessageDialog(null, "Masukkan setidaknya 1");
        } else {
            JOptionPane.showMessageDialog(null, "Berhasil ditambahkan");
            int y = 30000 * (int) jumlah4.getValue();
            Tbdata.setValueAt(menu4.getText(), x, 0);
            Tbdata.setValueAt(jumlah4.getValue(), x, 1);
            Tbdata.setValueAt(y, x, 2);
            x = x + 1;
        }
    }//GEN-LAST:event_pesan4ActionPerformed

    private void panelMenu8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMenu8MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_panelMenu8MouseClicked

    private void pesan5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesan5ActionPerformed
        if ((int) jumlah5.getValue() == 0){
            JOptionPane.showMessageDialog(null, "Masukkan setidaknya 1");
        } else {
            JOptionPane.showMessageDialog(null, "Berhasil ditambahkan");
            int y = 75000 * (int) jumlah5.getValue();
            Tbdata.setValueAt(menu5.getText(), x, 0);
            Tbdata.setValueAt(jumlah5.getValue(), x, 1);
            Tbdata.setValueAt(y, x, 2);
            x = x + 1;
        }
    }//GEN-LAST:event_pesan5ActionPerformed

    private void panelMenu9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMenu9MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_panelMenu9MouseClicked

    private void pesan6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesan6ActionPerformed
        if ((int) jumlah6.getValue() == 0){
            JOptionPane.showMessageDialog(null, "Masukkan setidaknya 1");
        } else {
            JOptionPane.showMessageDialog(null, "Berhasil ditambahkan");
            int y = 35000 * (int) jumlah6.getValue();
            Tbdata.setValueAt(menu6.getText(), x, 0);
            Tbdata.setValueAt(jumlah6.getValue(), x, 1);
            Tbdata.setValueAt(y, x, 2);
            x = x + 1;
        }
    }//GEN-LAST:event_pesan6ActionPerformed

    private void panelMenu10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMenu10MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_panelMenu10MouseClicked

    private void pesan7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesan7ActionPerformed
        if ((int) jumlah7.getValue() == 0){
            JOptionPane.showMessageDialog(null, "Masukkan setidaknya 1");
        } else {
            JOptionPane.showMessageDialog(null, "Berhasil ditambahkan");
            int y = 5000 * (int) jumlah7.getValue();
            Tbdata.setValueAt(menu7.getText(), x, 0);
            Tbdata.setValueAt(jumlah7.getValue(), x, 1);
            Tbdata.setValueAt(y, x, 2);
            x = x + 1;
        }
    }//GEN-LAST:event_pesan7ActionPerformed

    private void panelMenu11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMenu11MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_panelMenu11MouseClicked

    private void pesan8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesan8ActionPerformed
        if ((int) jumlah8.getValue() == 0){
            JOptionPane.showMessageDialog(null, "Masukkan setidaknya 1");
        } else {
            JOptionPane.showMessageDialog(null, "Berhasil ditambahkan");
            int y = 5000 * (int) jumlah8.getValue();
            Tbdata.setValueAt(menu8.getText(), x, 0);
            Tbdata.setValueAt(jumlah8.getValue(), x, 1);
            Tbdata.setValueAt(y, x, 2);
            x = x + 1;
        }
    }//GEN-LAST:event_pesan8ActionPerformed

    private void panelMenu12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMenu12MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_panelMenu12MouseClicked

    private void pesan9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesan9ActionPerformed
        if ((int) jumlah9.getValue() == 0){
            JOptionPane.showMessageDialog(null, "Masukkan setidaknya 1");
        } else {
            JOptionPane.showMessageDialog(null, "Berhasil ditambahkan");
            int y = 8000 * (int) jumlah9.getValue();
            Tbdata.setValueAt(menu9.getText(), x, 0);
            Tbdata.setValueAt(jumlah9.getValue(), x, 1);
            Tbdata.setValueAt(y, x, 2);
            x = x + 1;
        }
    }//GEN-LAST:event_pesan9ActionPerformed

    private void panelMenu13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelMenu13MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_panelMenu13MouseClicked

    private void hapusPesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusPesanActionPerformed
       
        Tbdata.setValueAt(null, Tbdata.getSelectedRow(), 0);
        Tbdata.setValueAt(null, Tbdata.getSelectedRow(), 1);
        Tbdata.setValueAt(null, Tbdata.getSelectedRow(), 2);       
    }//GEN-LAST:event_hapusPesanActionPerformed

    private void konfirButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_konfirButtonMouseClicked
        int x = 10;
        Object value = Tbdata.getValueAt(0, 0);       
        Object value1 = Tbdata.getValueAt(1, 0);
        Object value2 = Tbdata.getValueAt(2, 0);
        if(Objects.isNull(value) && Objects.isNull(value1) && Objects.isNull(value2)){
            JOptionPane.showMessageDialog(null, "Minimal pesanlah 1 (walaupun yang murah)");
        }else{
            Pembayaran bayar = new Pembayaran();
            bayar.setVisible(true);
            this.dispose();            
        }
        
    }//GEN-LAST:event_konfirButtonMouseClicked

    private void totalTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalTxtActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int x = 2;
        int totalHarga = 0;
        DefaultTableModel model = (DefaultTableModel) Tbdata.getModel();
        for (int rowIndex = 0; rowIndex < model.getRowCount(); rowIndex++) {
            Object value = model.getValueAt(rowIndex, x);
            if (value != null) {
                int harga = (int) value;
                totalHarga += harga;
            }
        }
        //int outputValue = 123;
        //String outputText = String.valueOf(outputValue);
        //totalTxt.setText(outputText);
        totalTxt.setText("Total Harga = Rp. " + totalHarga);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void metodePembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_metodePembayaranActionPerformed
        Pembayaran pembayaran = new Pembayaran();
        pembayaran.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_metodePembayaranActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HalamanProduk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HalamanProduk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HalamanProduk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HalamanProduk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HalamanProduk().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tbdata;
    private javax.swing.JButton hapusPesan;
    private javax.swing.JLabel harga1;
    private javax.swing.JLabel harga2;
    private javax.swing.JLabel harga3;
    private javax.swing.JLabel harga4;
    private javax.swing.JLabel harga5;
    private javax.swing.JLabel harga6;
    private javax.swing.JLabel harga7;
    private javax.swing.JLabel harga8;
    private javax.swing.JLabel harga9;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jumlah1;
    private javax.swing.JSpinner jumlah2;
    private javax.swing.JSpinner jumlah3;
    private javax.swing.JSpinner jumlah4;
    private javax.swing.JSpinner jumlah5;
    private javax.swing.JSpinner jumlah6;
    private javax.swing.JSpinner jumlah7;
    private javax.swing.JSpinner jumlah8;
    private javax.swing.JSpinner jumlah9;
    private javax.swing.JLabel konfirButton;
    private javax.swing.JLabel menu1;
    private javax.swing.JLabel menu2;
    private javax.swing.JLabel menu3;
    private javax.swing.JLabel menu4;
    private javax.swing.JLabel menu5;
    private javax.swing.JLabel menu6;
    private javax.swing.JLabel menu7;
    private javax.swing.JLabel menu8;
    private javax.swing.JLabel menu9;
    private javax.swing.JButton metodePembayaran;
    private javax.swing.JPanel panelMenu1;
    private javax.swing.JPanel panelMenu10;
    private javax.swing.JPanel panelMenu11;
    private javax.swing.JPanel panelMenu12;
    private javax.swing.JPanel panelMenu13;
    private javax.swing.JPanel panelMenu3;
    private javax.swing.JPanel panelMenu7;
    private javax.swing.JPanel panelMenu8;
    private javax.swing.JPanel panelMenu9;
    private javax.swing.JButton pesan1;
    private javax.swing.JButton pesan2;
    private javax.swing.JButton pesan3;
    private javax.swing.JButton pesan4;
    private javax.swing.JButton pesan5;
    private javax.swing.JButton pesan6;
    private javax.swing.JButton pesan7;
    private javax.swing.JButton pesan8;
    private javax.swing.JButton pesan9;
    private javax.swing.JTextField totalTxt;
    // End of variables declaration//GEN-END:variables

    private void setText(String toatl_Harga__) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
